#!/bin/bash

# Log file to accumulate results
logfile="results.log"
echo "Starting the log file at $(date)" > $logfile

for trace in {1..1}; do
    domain="/pddl/domain.pddl"
    problem="/pddl/problem$.pddl"

    # Run the Symba2*
    ./plan "$domain" "$problem" "/pddl/plan_$trace.sas"

    # Extract the specific part of the output and append to log file
    echo "Results for trace #$trace:" >> $logfile
    echo "Completed trace #$trace at $(date)" >> $logfile
done
