(define (problem trace_Alignment_Problem_25_Noisy.pddl)
	(:domain traceAlignment)

	(:objects
		t0 t1 t2 t3 t4 t5 t6 t7 t8 t9 t10 t11 t12 t13 t14 t15 t16 t17 t18 t19 t20 t21 - trace_state
		s0 s1 - automaton_state
		Handle_Case Inbound_Call Make_credit_offer Check_credit_history Check_income_sources Handle_Email Assess_application Credit_application_processed - activity
		Handle_Case_assign Handle_Case_start Handle_Case_complete Inbound_Call_assign Inbound_Call_start Inbound_Call_complete Make_credit_offer_assign Make_credit_offer_start Make_credit_offer_complete Check_credit_history_assign Check_credit_history_start Check_credit_history_complete Check_income_sources_assign Check_income_sources_start Check_income_sources_complete Handle_Email_assign Handle_Email_start Handle_Email_complete Assess_application_assign Assess_application_start Assess_application_complete Credit_application_processed_assign Credit_application_processed_start Credit_application_processed_complete - lifecycle_activity
	)

	(:init
		(final_state s0)
		(cur_lifecycle_state Handle_Case init_state)
		(final_lifecycle_state Handle_Case completed_state)
		(lifecycle_activity_of Handle_Case Handle_Case_assign)
		(lifecycle_activity_of Handle_Case Handle_Case_start)
		(lifecycle_activity_of Handle_Case Handle_Case_complete)
		(lifecycle init_state Handle_Case_assign assigned_state)
		(lifecycle assigned_state Handle_Case_start started_state)
		(lifecycle started_state Handle_Case_complete completed_state)
		(cur_lifecycle_state Inbound_Call init_state)
		(final_lifecycle_state Inbound_Call completed_state)
		(lifecycle_activity_of Inbound_Call Inbound_Call_assign)
		(lifecycle_activity_of Inbound_Call Inbound_Call_start)
		(lifecycle_activity_of Inbound_Call Inbound_Call_complete)
		(lifecycle init_state Inbound_Call_assign assigned_state)
		(lifecycle assigned_state Inbound_Call_start started_state)
		(lifecycle started_state Inbound_Call_complete completed_state)
		(cur_state s0)
		(automaton s0 Handle_Case_start s1)
		(automaton s1 Inbound_Call_complete s0)
		(cur_state t0)
		(trace t0 Make_credit_offer_assign t1)
		(cur_lifecycle_state Make_credit_offer init_state)
		(final_lifecycle_state Make_credit_offer completed_state)
		(lifecycle_activity_of Make_credit_offer Make_credit_offer_assign)
		(lifecycle init_state Make_credit_offer_assign assigned_state)
		(lifecycle_activity_of Make_credit_offer Make_credit_offer_start)
		(lifecycle assigned_state Make_credit_offer_start started_state)
		(lifecycle_activity_of Make_credit_offer Make_credit_offer_complete)
		(lifecycle started_state Make_credit_offer_complete completed_state)
		(trace t1 Make_credit_offer_complete t2)
		(trace t2 Check_credit_history_assign t3)
		(cur_lifecycle_state Check_credit_history init_state)
		(final_lifecycle_state Check_credit_history completed_state)
		(lifecycle_activity_of Check_credit_history Check_credit_history_assign)
		(lifecycle init_state Check_credit_history_assign assigned_state)
		(lifecycle_activity_of Check_credit_history Check_credit_history_start)
		(lifecycle assigned_state Check_credit_history_start started_state)
		(lifecycle_activity_of Check_credit_history Check_credit_history_complete)
		(lifecycle started_state Check_credit_history_complete completed_state)
		(trace t3 Check_credit_history_start t4)
		(trace t4 Check_income_sources_assign t5)
		(cur_lifecycle_state Check_income_sources init_state)
		(final_lifecycle_state Check_income_sources completed_state)
		(lifecycle_activity_of Check_income_sources Check_income_sources_assign)
		(lifecycle init_state Check_income_sources_assign assigned_state)
		(lifecycle_activity_of Check_income_sources Check_income_sources_start)
		(lifecycle assigned_state Check_income_sources_start started_state)
		(lifecycle_activity_of Check_income_sources Check_income_sources_complete)
		(lifecycle started_state Check_income_sources_complete completed_state)
		(trace t5 Check_income_sources_start t6)
		(trace t6 Handle_Case_complete t7)
		(trace t7 Inbound_Call_complete t8)
		(trace t8 Check_credit_history_complete t9)
		(trace t9 Inbound_Call_assign t10)
		(trace t10 Handle_Email_assign t11)
		(cur_lifecycle_state Handle_Email init_state)
		(final_lifecycle_state Handle_Email completed_state)
		(lifecycle_activity_of Handle_Email Handle_Email_assign)
		(lifecycle init_state Handle_Email_assign assigned_state)
		(lifecycle_activity_of Handle_Email Handle_Email_start)
		(lifecycle assigned_state Handle_Email_start started_state)
		(lifecycle_activity_of Handle_Email Handle_Email_complete)
		(lifecycle started_state Handle_Email_complete completed_state)
		(trace t11 Handle_Email_start t12)
		(trace t12 Assess_application_assign t13)
		(cur_lifecycle_state Assess_application init_state)
		(final_lifecycle_state Assess_application completed_state)
		(lifecycle_activity_of Assess_application Assess_application_assign)
		(lifecycle init_state Assess_application_assign assigned_state)
		(lifecycle_activity_of Assess_application Assess_application_start)
		(lifecycle assigned_state Assess_application_start started_state)
		(lifecycle_activity_of Assess_application Assess_application_complete)
		(lifecycle started_state Assess_application_complete completed_state)
		(trace t13 Assess_application_complete t14)
		(trace t14 Make_credit_offer_start t15)
		(trace t15 Check_income_sources_complete t16)
		(trace t16 Credit_application_processed_assign t17)
		(cur_lifecycle_state Credit_application_processed init_state)
		(final_lifecycle_state Credit_application_processed completed_state)
		(lifecycle_activity_of Credit_application_processed Credit_application_processed_assign)
		(lifecycle init_state Credit_application_processed_assign assigned_state)
		(lifecycle_activity_of Credit_application_processed Credit_application_processed_start)
		(lifecycle assigned_state Credit_application_processed_start started_state)
		(lifecycle_activity_of Credit_application_processed Credit_application_processed_complete)
		(lifecycle started_state Credit_application_processed_complete completed_state)
		(trace t17 Credit_application_processed_complete t18)
		(trace t18 Assess_application_start t19)
		(trace t19 Handle_Email_assign t20)
		(trace t20 Handle_Case_complete t21)
		(final_state t21)
	)

	(:goal
		(and
			(cur_state s0)
			(cur_lifecycle_state Handle_Case completed_state)
			(cur_lifecycle_state Inbound_Call completed_state)
			(cur_lifecycle_state Make_credit_offer completed_state)
			(cur_lifecycle_state Check_credit_history completed_state)
			(cur_lifecycle_state Check_income_sources completed_state)
			(cur_lifecycle_state Handle_Email completed_state)
			(cur_lifecycle_state Assess_application completed_state)
			(cur_lifecycle_state Credit_application_processed completed_state)
			(cur_state t21)
		)
	)
	(:metric minimize (total-cost))
)
