(define (problem trace_Alignment_Problem_Case_9_Noisy.pddl)
	(:domain traceAlignment)

	(:objects
		t0 t1 t2 t3 t4 t5 t6 t7 t8 - trace_state
		s0 s1 s2 s3 - automaton_state
		Handle_Case Inbound_Call Call_Outbound Inbound_Email Handle_Email - activity
		Handle_Case_assign Handle_Case_start Handle_Case_complete Inbound_Call_assign Inbound_Call_start Inbound_Call_complete Call_Outbound_assign Call_Outbound_start Call_Outbound_complete Inbound_Email_assign Inbound_Email_start Inbound_Email_complete Handle_Email_assign Handle_Email_start Handle_Email_complete - lifecycle_activity
	)

	(:init
		(final_state s1)
		(cur_lifecycle_state Handle_Case init_state)
		(final_lifecycle_state Handle_Case completed_state)
		(lifecycle_activity_of Handle_Case Handle_Case_assign)
		(lifecycle_activity_of Handle_Case Handle_Case_start)
		(lifecycle_activity_of Handle_Case Handle_Case_complete)
		(lifecycle init_state Handle_Case_assign assigned_state)
		(lifecycle init_state Handle_Case_start sink_state)
		(lifecycle init_state Handle_Case_complete sink_state)
		(lifecycle assigned_state Handle_Case_start started_state)
		(lifecycle assigned_state Handle_Case_assign sink_state)
		(lifecycle assigned_state Handle_Case_complete sink_state)
		(lifecycle started_state Handle_Case_complete completed_state)
		(lifecycle started_state Handle_Case_assign sink_state)
		(lifecycle started_state Handle_Case_start sink_state)
		(lifecycle completed_state Handle_Case_assign sink_state)
		(lifecycle completed_state Handle_Case_start sink_state)
		(lifecycle completed_state Handle_Case_complete sink_state)
		(cur_lifecycle_state Inbound_Call init_state)
		(final_lifecycle_state Inbound_Call completed_state)
		(lifecycle_activity_of Inbound_Call Inbound_Call_assign)
		(lifecycle_activity_of Inbound_Call Inbound_Call_start)
		(lifecycle_activity_of Inbound_Call Inbound_Call_complete)
		(lifecycle init_state Inbound_Call_assign assigned_state)
		(lifecycle init_state Inbound_Call_start sink_state)
		(lifecycle init_state Inbound_Call_complete sink_state)
		(lifecycle assigned_state Inbound_Call_start started_state)
		(lifecycle assigned_state Inbound_Call_assign sink_state)
		(lifecycle assigned_state Inbound_Call_complete sink_state)
		(lifecycle started_state Inbound_Call_complete completed_state)
		(lifecycle started_state Inbound_Call_assign sink_state)
		(lifecycle started_state Inbound_Call_start sink_state)
		(lifecycle completed_state Inbound_Call_assign sink_state)
		(lifecycle completed_state Inbound_Call_start sink_state)
		(lifecycle completed_state Inbound_Call_complete sink_state)
		(cur_lifecycle_state Call_Outbound init_state)
		(final_lifecycle_state Call_Outbound completed_state)
		(lifecycle_activity_of Call_Outbound Call_Outbound_assign)
		(lifecycle_activity_of Call_Outbound Call_Outbound_start)
		(lifecycle_activity_of Call_Outbound Call_Outbound_complete)
		(lifecycle init_state Call_Outbound_assign assigned_state)
		(lifecycle init_state Call_Outbound_start sink_state)
		(lifecycle init_state Call_Outbound_complete sink_state)
		(lifecycle assigned_state Call_Outbound_start started_state)
		(lifecycle assigned_state Call_Outbound_assign sink_state)
		(lifecycle assigned_state Call_Outbound_complete sink_state)
		(lifecycle started_state Call_Outbound_complete completed_state)
		(lifecycle started_state Call_Outbound_assign sink_state)
		(lifecycle started_state Call_Outbound_start sink_state)
		(lifecycle completed_state Call_Outbound_assign sink_state)
		(lifecycle completed_state Call_Outbound_start sink_state)
		(lifecycle completed_state Call_Outbound_complete sink_state)
		(cur_state s0)
		(automaton s0 Inbound_Call_complete s3)
		(automaton s0 Call_Outbound_complete s2)
		(automaton s1 Handle_Case_start s2)
		(automaton s2 Inbound_Call_complete s1)
		(automaton s3 Handle_Case_start s0)
		(automaton s3 Call_Outbound_complete s1)
		(cur_state t0)
		(trace t0 Inbound_Email_assign t1)
		(cur_lifecycle_state Inbound_Email init_state)
		(final_lifecycle_state Inbound_Email completed_state)
		(lifecycle_activity_of Inbound_Email Inbound_Email_assign)
		(lifecycle init_state Inbound_Email_assign assigned_state)
		(lifecycle init_state Inbound_Email_start sink_state)
		(lifecycle init_state Inbound_Email_complete sink_state)
		(lifecycle_activity_of Inbound_Email Inbound_Email_start)
		(lifecycle assigned_state Inbound_Email_start started_state)
		(lifecycle assigned_state Inbound_Email_assign sink_state)
		(lifecycle assigned_state Inbound_Email_complete sink_state)
		(lifecycle_activity_of Inbound_Email Inbound_Email_complete)
		(lifecycle started_state Inbound_Email_complete completed_state)
		(lifecycle started_state Inbound_Email_assign sink_state)
		(lifecycle started_state Inbound_Email_start sink_state)
		(lifecycle completed_state Inbound_Email_assign sink_state)
		(lifecycle completed_state Inbound_Email_start sink_state)
		(lifecycle completed_state Inbound_Email_complete sink_state)
		(trace t1 Inbound_Email_start t2)
		(trace t2 Inbound_Email_complete t3)
		(trace t3 Call_Outbound_assign t4)
		(trace t4 Call_Outbound_start t5)
		(trace t5 Call_Outbound_complete t6)
		(trace t6 Handle_Email_assign t7)
		(cur_lifecycle_state Handle_Email init_state)
		(final_lifecycle_state Handle_Email completed_state)
		(lifecycle_activity_of Handle_Email Handle_Email_assign)
		(lifecycle init_state Handle_Email_assign assigned_state)
		(lifecycle init_state Handle_Email_start sink_state)
		(lifecycle init_state Handle_Email_complete sink_state)
		(lifecycle_activity_of Handle_Email Handle_Email_start)
		(lifecycle assigned_state Handle_Email_start started_state)
		(lifecycle assigned_state Handle_Email_assign sink_state)
		(lifecycle assigned_state Handle_Email_complete sink_state)
		(lifecycle_activity_of Handle_Email Handle_Email_complete)
		(lifecycle started_state Handle_Email_complete completed_state)
		(lifecycle started_state Handle_Email_assign sink_state)
		(lifecycle started_state Handle_Email_start sink_state)
		(lifecycle completed_state Handle_Email_assign sink_state)
		(lifecycle completed_state Handle_Email_start sink_state)
		(lifecycle completed_state Handle_Email_complete sink_state)
		(trace t7 Handle_Email_complete t8)
		(final_state t8)
	)

	(:goal
		(and
			(cur_state s1)
			(cur_lifecycle_state Handle_Case completed_state)
			(cur_lifecycle_state Inbound_Call completed_state)
			(cur_lifecycle_state Call_Outbound completed_state)
			(cur_lifecycle_state Inbound_Email completed_state)
			(cur_lifecycle_state Handle_Email completed_state)
			(cur_state t8)
		)
	)
	(:metric minimize (total-cost))
)
