parameters:
  constraints_declare:
    - 1
    - 3
    - 5
    - 7
  lifecycle_trace_alphabet:
    - 8
    - 12
  traces_length:
    - 10
    - 20
    - 30
  noise:
    - 0
    - 10
    - 20
    - 30
  executed_traces_per_execution:
    - 20
time:
  generating models: 45 min
  generating logs rum: 15 min
  generating noise logs: 35 min
generate order:
  - declare files (from smaller to larger, first one alphabet)
  - logs
  - noisy logs
  - dot files
