parameters:
  constraints_declare:
    - 1
    - 3
    - 5
    - 7
  lifecycle_trace_alphabet:
    - 5
    - 10
  traces_length:
    - 10
    - 20
    - 30
  noise:
    - 0
    - 10
    - 20
    - 30
  executed_traces_per_execution:
    - 20
