#!/bin/bash
cd /Users/applem2/Downloads/Work/tesi/fast-downward-23.06/
date1=$(date +%s%N | cut -b1-13)
searchtime=0
traces=0
for f in Conformance_Checking/domain*.pddl
do
domain="Conformance_Checking/domain$f.pddl"
problem="Conformance_Checking/problem1.pddl"
prima=$(date +%s%N | cut -b1-13)
#echo $traces
./fast-downward.py $domain $problem --heuristic "hff=ff()"  --heuristic "hcea=cea()" --search "astar(blind())" < /Users/applem2/Downloads/Work/tesi/fast-downward-23.06/output.txt
dopo=$(date +%s%N | cut -b1-13)
searchtime=$(($searchtime+$dopo-$prima))
#echo $traces
done
date2=$(date +%s%N | cut -b1-13)
diff=$(($date2-$date1))
transtime=$(($diff-$searchtime))
#echo $date1
#echo $date2
echo "the duration is: $diff ms. for $traces traces"
echo "the search time is: $searchtime ms."
echo "the translation time is: $transtime ms."
#>/dev/null
