#!/bin/bash

cd /Users/applem2/Downloads/TESI/seq_opt_symba_2/ || exit

logfile="symba2_$1_$2_$3_$4_.txt"

cp /Users/applem2/Downloads/TESI/Project/Aligner/Plan-based_Data_Aware_Declarative_Conf_Checker/seq-opt-symba-2/Conformance_Checking/* "Conformance_Checking/"

echo "Starting the log file at $(date)" > "$logfile"

for trace in {1..1}; do
    domain="Conformance_Checking/domain${trace}.pddl"
    problem="Conformance_Checking/problem${trace}.pddl"

    output=$(./plan $domain $problem /pddl/plan.sas 2>&1)

    echo "" >> "$logfile"
    echo "Results for trace #$trace:" >> "$logfile"
    echo "$output" | grep -E 'Plan length:|Plan cost:|Search time:|Total time:' | sed -E 's/\[.*\] //g' >> "$logfile"
    echo "Completed trace #$trace" >> "$logfile"
done