#!/bin/bash

cd /Users/applem2/Downloads/TESI/fast-downward-23.06/ || exit

logfile="fast-downward_$1_$2_$3_$4_$5_.txt"

cp /Users/applem2/Downloads/TESI/Project/Aligner/Plan-based_Data_Aware_Declarative_Conf_Checker/fast-downward/Conformance_Checking/* "Conformance_Checking/"

echo "Starting the log file at $(date)" > "$logfile"

for trace in {1..20}; do
    domain="Conformance_Checking/domain${trace}.pddl"
    problem="Conformance_Checking/problem${trace}.pddl"

    output=$(./fast-downward.py "$domain" "$problem" --search "astar(blind())" 2>&1)

    echo "" >> "$logfile"
    echo "Results for trace #$trace:" >> "$logfile"
    echo "$output" | grep -E 'Plan length:|Plan cost:|Search time:|Total time:' | sed -E 's/\[.*\] //g' >> "$logfile"
    echo "Completed trace #$trace" >> "$logfile"
done
