#!/bin/bash

# Path to compiled classes
COMPILED_CLASSES_PATH="/Users/applem2/Downloads/TESI/Project/Aligner/out/production/Aligner"

# Paths to external libraries (from the Eclipse .classpath file)
LIBRARY_PATHS=(
    "/Users/applem2/Downloads/TESI/Project/Aligner/Plan-based_Data_Aware_Declarative_Conf_Checker/lib/DeclareVisualizer.jar"
    "/Users/applem2/Downloads/TESI/Project/Aligner/Plan-based_Data_Aware_Declarative_Conf_Checker/lib/guava-16.0.1.jar"
    "/Users/applem2/Downloads/TESI/Project/Aligner/Plan-based_Data_Aware_Declarative_Conf_Checker/lib/OpenXES.jar"
    "/Users/applem2/Downloads/TESI/Project/Aligner/Plan-based_Data_Aware_Declarative_Conf_Checker/lib/OpenXES-XStream.jar"
    "/Users/applem2/Downloads/TESI/Project/Aligner/Plan-based_Data_Aware_Declarative_Conf_Checker/lib/java-cup-11b.jar"
    "/Users/applem2/Downloads/TESI/Project/Aligner/Plan-based_Data_Aware_Declarative_Conf_Checker/lib/LTL2Automaton.jar"
    "/Users/applem2/Downloads/TESI/Project/Aligner/Plan-based_Data_Aware_Declarative_Conf_Checker/lib/lpsolve55j.jar"
    "/Users/applem2/Downloads/TESI/Project/Aligner/Plan-based_Data_Aware_Declarative_Conf_Checker/lib/javailp-1.2a.jar"
    "/Users/applem2/Downloads/TESI/Project/Aligner/Plan-based_Data_Aware_Declarative_Conf_Checker/lib/gs-core-2.0.jar"
)

# Join compiled class path with library paths
CLASSPATH="$COMPILED_CLASSES_PATH:$(IFS=:; echo "${LIBRARY_PATHS[*]}")"


# List of log files
LOG_FILES=(
# noise 0 10 20 30
# trace alphabet 5 10
# trace length 10 20 30
    "/Users/applem2/Downloads/TESI/Project/Aligner/Plan-based_Data_Aware_Declarative_Conf_Checker/resources/log-files/Data-Aware/5-CONSTRAINTS/2_mod/length_20.xes_atomized_1.xes"
)

# List of constraint files
CONSTRAINT_FILES=(
# constraints 1 3 5 7
"/Users/applem2/Downloads/TESI/Project/Aligner/Plan-based_Data_Aware_Declarative_Conf_Checker/resources/declarative-models/DECLARE-models/10-CONSTRAINTS/1_decl.xml"

)

PLANNERS=("fd" "symba")


for PLANNER in "${PLANNERS[@]}"; do
    for CONSTRAINT in "${CONSTRAINT_FILES[@]}"; do
        for LOG in "${LOG_FILES[@]}"; do

            # Extract logging information from file names
            if [[ "$LOG_NAME" =~ noise-([0-9]+) ]]; then
                NOISE="${BASH_REMATCH[1]}"
            fi
            if [[ "$LOG_NAME" =~ alphabet-([0-9]+) ]]; then
                TRACE_ALPHABET="${BASH_REMATCH[1]}"
            fi
            if [[ "$LOG_NAME" =~ length-([0-9]+) ]]; then
                TRACE_LENGTH="${BASH_REMATCH[1]}"
            fi
            if [[ "$CONSTRAINT_NAME" =~ length-([0-9]+) ]]; then
                CONSTRAINTS_NUM="${BASH_REMATCH[1]}"
            fi
            PLANNER_NAME=$(basename "$PLANNER")

            echo -e "##### RUNNING WITH:\n$PLANNER_NAME\n$NOISE\n$TRACE_ALPHABET\n$TRACE_LENGTH\n$CONSTRAINTS_NUM"

            # Run the Java program with the current combination of log file, constraint file, and planner
            java -cp "$CLASSPATH" main.Main "$PLANNER" "$LOG" "$CONSTRAINT"

            echo "####################################"
            echo ""
        done
    done
done
